# Generated by Django 5.0.4 on 2024-07-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                ("descripcion", models.TextField(verbose_name="Descripcion")),
                (
                    "imagen_fondo",
                    models.ImageField(upload_to="home/", verbose_name="Img Fondo"),
                ),
            ],
            options={
                "verbose_name": "Home",
                "verbose_name_plural": "Home",
            },
        ),
    ]
