# Generated by Django 5.0.4 on 2024-07-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="descripcion",
            field=models.TextField(
                default="I'm a professional content creator from Argentina",
                verbose_name="Descripcion",
            ),
        ),
        migrations.AlterField(
            model_name="home",
            name="titulo",
            field=models.CharField(
                default="SPITTER", max_length=100, verbose_name="Titulo"
            ),
        ),
    ]
