# Generated by Django 5.0.4 on 2024-07-17 16:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_home_descripcion_alter_home_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="imagen_fondo",
            field=models.ImageField(
                upload_to="home/",
                validators=[core.models.validate_image_size],
                verbose_name="Img Fondo",
            ),
        ),
    ]
