# Generated by Django 5.0.4 on 2024-07-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="icon_color",
            field=models.CharField(
                default="darkred",
                help_text="Colores disponibles: orange, yellow, pink, black, silver, gray, white, maroon, red, purple, fuchsia, green, lime, olive, yellow, navy, blue, teal, aqua",
                max_length=50,
            ),
        ),
    ]
