# Generated by Django 5.0.4 on 2024-07-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=100, verbose_name="Grado")),
                (
                    "institution",
                    models.CharField(max_length=100, verbose_name="Instituto"),
                ),
                ("start_year", models.IntegerField(verbose_name="Año inicio")),
                (
                    "end_year",
                    models.IntegerField(blank=True, null=True, verbose_name="Año fin"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
            ],
            options={
                "verbose_name": "Educacion",
                "verbose_name_plural": "Educaciones",
                "ordering": ["start_year"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titulo")),
                ("company", models.CharField(max_length=100, verbose_name="Compañia")),
                ("start_year", models.IntegerField(verbose_name="Año inicio")),
                (
                    "end_year",
                    models.IntegerField(blank=True, null=True, verbose_name="Año fin"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "responsibilities",
                    models.TextField(verbose_name="Responsabilidades"),
                ),
            ],
            options={
                "verbose_name": "Experiencia",
                "verbose_name_plural": "Experiencias",
                "ordering": ["start_year"],
            },
        ),
    ]
