# Generated by Django 5.0.4 on 2024-07-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tittle_section",
                    models.CharField(
                        default="About",
                        max_length=100,
                        verbose_name="Título de Sección",
                    ),
                ),
                (
                    "desc_section",
                    models.TextField(
                        default="Magnam dolores commodi suscipit...",
                        verbose_name="Descripción de Sección",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        default="about/default.jpg",
                        upload_to="about/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Content Creator, Video Editor, and Music Producer",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "desc_short",
                    models.TextField(
                        default="Lorem ipsum dolor sit amet...",
                        verbose_name="Descripción Corta",
                    ),
                ),
                (
                    "birthday",
                    models.CharField(
                        default="1 May 1995", max_length=100, verbose_name="Cumpleaños"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        default="www.example.com", verbose_name="Sitio Web"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+123 456 7890", max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="New York, USA", max_length=100, verbose_name="Ciudad"
                    ),
                ),
                ("age", models.IntegerField(default=21, verbose_name="Edad")),
                (
                    "degree",
                    models.CharField(
                        default="Master", max_length=50, verbose_name="Grado"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="email@example.com",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "freelance",
                    models.CharField(
                        default="Available", max_length=50, verbose_name="Freelance"
                    ),
                ),
                (
                    "desc_long",
                    models.TextField(
                        default="Officiis eligendi itaque...",
                        verbose_name="Descripción Larga",
                    ),
                ),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "About",
            },
        ),
    ]
