# Generated by Django 5.0.4 on 2024-07-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre Habilidad"),
                ),
                ("percentage", models.IntegerField(verbose_name="Porcentaje")),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.CreateModel(
            name="SkillDesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tittle_section",
                    models.CharField(
                        default="Skills",
                        max_length=100,
                        verbose_name="Título de Sección",
                    ),
                ),
                (
                    "desc_section",
                    models.TextField(
                        default="Magnam dolores commodi suscipit...",
                        verbose_name="Descripción de Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descripcion de Habilidades",
                "verbose_name_plural": "Descripciones de Habilidades",
            },
        ),
    ]
