# Generated by Django 5.0.4 on 2024-07-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_skill_skilldesc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Título del Hecho"),
                ),
                (
                    "end_value",
                    models.IntegerField(default=0, verbose_name="Valor Final"),
                ),
                ("duration", models.IntegerField(default=1, verbose_name="Duración")),
            ],
            options={
                "verbose_name": "Hecho",
                "verbose_name_plural": "Hechos",
            },
        ),
        migrations.CreateModel(
            name="FactDesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tittle_section",
                    models.CharField(
                        default="Facts",
                        max_length=100,
                        verbose_name="Título de Sección",
                    ),
                ),
                (
                    "desc_section",
                    models.TextField(
                        default="Magnam dolores commodi suscipit...",
                        verbose_name="Descripción de Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descripcion de Datos",
                "verbose_name_plural": "Descripciones de Datos",
            },
        ),
    ]
