# Generated by Django 5.0.4 on 2024-07-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_fact_factdesc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=100, verbose_name="Nombre del autor"),
                ),
                (
                    "author_position",
                    models.CharField(max_length=100, verbose_name="Posición del autor"),
                ),
                (
                    "testimonial_text",
                    models.TextField(verbose_name="Texto del testimonio"),
                ),
                (
                    "testimonial_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Imagen del testimonio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonio",
                "verbose_name_plural": "Testimonios",
            },
        ),
        migrations.CreateModel(
            name="TestimonialDesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tittle_section",
                    models.CharField(
                        default="Testimonials",
                        max_length=100,
                        verbose_name="Título de Sección",
                    ),
                ),
                (
                    "desc_section",
                    models.TextField(
                        default="Magnam dolores commodi suscipit...",
                        verbose_name="Descripción de Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descripcion de Testimonios",
                "verbose_name_plural": "Descripciones de Testimonios",
            },
        ),
        migrations.AlterModelOptions(
            name="fact",
            options={"verbose_name": "Dato", "verbose_name_plural": "Datos"},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "Habilidad", "verbose_name_plural": "Habilidades"},
        ),
        migrations.AlterField(
            model_name="fact",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Título del Dato"),
        ),
    ]
