# Generated by Django 5.0.4 on 2024-07-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioitem",
            name="category",
            field=models.CharField(
                choices=[("Audio", "Audio"), ("Video", "Video"), ("Otros", "Otros")],
                max_length=50,
                verbose_name="Tipo de Filtro",
            ),
        ),
    ]
