# Generated by Django 5.0.4 on 2024-07-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tittle_section",
                    models.CharField(
                        default="Contact Information",
                        max_length=100,
                        verbose_name="Título de Sección",
                    ),
                ),
                (
                    "desc_section",
                    models.TextField(
                        default="Aquí puede encontrar mi información de contacto...",
                        verbose_name="Descripción de Sección",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Argentina", max_length=255, verbose_name="Ubicación"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="contact.spitterworld@gmail.com",
                        max_length=254,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "call",
                    models.CharField(
                        default="No especificado",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
            ],
            options={
                "verbose_name": "Información de Contacto",
                "verbose_name_plural": "Información de Contacto",
            },
        ),
    ]
