# Generated by Django 5.0.4 on 2024-07-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="SPITTER", max_length=100, verbose_name="Nombre Sitio"
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        default="© Copyright Spitty. All Rights Reserved",
                        max_length=255,
                        verbose_name="Copyright",
                    ),
                ),
            ],
            options={
                "verbose_name": "Config",
                "verbose_name_plural": "Configs",
            },
        ),
    ]
