# Generated by Django 5.0.4 on 2024-07-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_social",
                    models.CharField(default="#", max_length=300, verbose_name="Redes"),
                ),
                (
                    "link_x",
                    models.CharField(default="#", max_length=300, verbose_name="X"),
                ),
                (
                    "link_fb",
                    models.CharField(
                        default="#", max_length=300, verbose_name="Facebook"
                    ),
                ),
                (
                    "link_ig",
                    models.CharField(
                        default="#", max_length=300, verbose_name="Instagram"
                    ),
                ),
                (
                    "link_in",
                    models.CharField(
                        default="#", max_length=300, verbose_name="Linkedin"
                    ),
                ),
                (
                    "link_tw",
                    models.CharField(
                        default="#", max_length=300, verbose_name="Twitch"
                    ),
                ),
                (
                    "link_yt",
                    models.CharField(
                        default="#", max_length=300, verbose_name="YouTube"
                    ),
                ),
                (
                    "link_sc",
                    models.CharField(
                        default="#", max_length=300, verbose_name="SoundCloud"
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Links",
                "verbose_name_plural": "Social Links",
            },
        ),
    ]
